### ISSUE TITLE
WP 6.0

### ISSUE THREAD

**Issue by Rahe** [BeAPI/bea-media-analytics#88]
Test and release new version compatible with WP 6.0 if needed

**Comment by porg** [comment]
1. Not having been aware of your plugin, I had submitted a user story + UX design for a minimal MVP to WP-Core:
[As a website editor I want to find out which media asset (image, video, etc) is used on which pages / posts](https://core.trac.wordpress.org/ticket/57616)
2. I was [made aware](https://core.trac.wordpress.org/ticket/57616#comment:4) of your plugin and realized it [fulfills most aspects of my MVP](https://core.trac.wordpress.org/ticket/57616#comment:5).
  - So yes, for starters I'd love to just use your plugin as-is in WP 6.x!
    - 🙁 But sadly your plugin fails fatally, see `php_error.log` below.
  - Maybe you also want look at some ideas in the proposal and also some of the ongoing discussion there.

## In WP 6.1.1 the plugin fails like this
- Both in the Media Library in List View and the Media Detail Page there's a banner hint on top saying:

  `As BEA - Media Analytics plugin has been activated, the process of indexing contents will silently launch himself soon.`
  (Note: The correct English pronoun for software/computer/machine is "it" so "launch itself" would be correct)
    
- That banner never goes a way. A look at `php_error.log` shows it died with a fatal error:

```
[03-Feb-2023 19:50:28 UTC] PHP Warning:  Undefined array key "file" in /my-document-root/wp-content/plugins/media-file-renamer/classes/rest.php on line 349
[03-Feb-2023 21:52:33 UTC] PHP Warning:  The magic method BEA\Media_Analytics\Singleton::__wakeup() must have public visibility in /my-document-root/wp-content/plugins/bea-media-analytics/classes/singleton.php on line 59
[03-Feb-2023 21:53:49 UTC] PHP Fatal error:  Uncaught Error: Non-static method BEA\Media_Analytics\Main::force_indexation() cannot be called statically in /my-document-root/wp-content/plugins/bea-media-analytics/classes/crons.php:44
Stack trace:
#0 /my-document-root/wp-includes/class-wp-hook.php(308): BEA\Media_Analytics\Crons->cron_force_indexation()
#1 /my-document-root/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /my-document-root/wp-includes/plugin.php(565): WP_Hook->do_action()
#3 /my-document-root/wp-cron.php(188): do_action_ref_array()
#4 {main}
  thrown in /my-document-root/wp-content/plugins/bea-media-analytics/classes/crons.php on line 44
```

**Comment by porg** [comment]
## How are the chances that this plugin gets updated for WP 6.x?
- Again my compliments: A real fundamental and hence cool feature to determine which media is used on which pages!
- As an agency your clients probably need that plugin for massive media management
  - Are they not updating to WP 6.x? And then possibly moaning about the plugin not working anymore?
  - Maybe that's a possible driver for continuing development…?
- Anyhow I'm grateful for any infos regarding development plans!

**Comment by petitphp** [comment]
Hi @porg 

Thanks for commenting on the issue with your findings.

We are in the process of testing the plugin on the latest version of PHP and WordPress. In addition to the PHP8 compatibility issue you mentioned, there might be another issue with the parsing of images for posts saved via Gutenberg.

We are working on a new release to address all the issues.

**Comment by porg** [comment]
Hi @petitphp,

1. glad to read that an update is in the works!

2. > … might be another issue with the parsing of images for posts saved via Gutenberg.
  - Yes media handling is a bit inconsistent in Wordpress… I had different outcomes regarding media when inserting via classical editor vs. block editor (Gutenberg) vs. media library upload dialog, and also classical media detail page vs. newer media detail modal popup behave differently regarding editing metadata.
  - Among other media bugs I had reported WordPress/gutenberg/issues/34149
    - Adam Silverstein wrote that Gutenberg deals with media through the REST API which differs to the regular media uploader. He wrote [this fix](https://github.com/WordPress/gutenberg/issues/34149#issuecomment-1416260545). Maybe this co-incidentially also helps your case…? At least I wanted to mention it to you.
